### ISSUE TITLE
USER STORY: Leave a comment

### ISSUE THREAD

**Issue by omurilolima** [omurilolima/book-club#7]
As a User, I want to leave a comment on a post.

### Comment model
<html>
<body>

Key | Name | Type | Extra Info
-- | -- | -- | --
ForeignKey | post | Post model | Cascade on delete
  | name | CharField | Max length 80
  | email | EmailField |  
  | body | TextField |  
  | created_on | DateTimeField | auto_now_add True
  | approved | BooleanField | default False

</body>
</html>

### Tasks
- [x] Install [Django Crispy Forms](https://django-crispy-forms.readthedocs.io/en/latest/index.html) library
- [x] Create forms.py file
- [x] Add form to post_detail.html
- [x] Add post method to PostDetail class
